In [2]:
import numpy as np

In [4]:
x=[1,2,3]

In [5]:
y=np.array(x)

In [6]:
y

array([1, 2, 3])

In [201]:
type(y)

numpy.ndarray

In [10]:
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [11]:
y/2

array([0.5, 1. , 1.5])

In [12]:
x = [1.5,2.5,3.5,4.4,5.5]
x

[1.5, 2.5, 3.5, 4.4, 5.5]

In [13]:
y = np.array(x)
y

array([1.5, 2.5, 3.5, 4.4, 5.5])

#### 2D array

In [15]:
x = [ [1,2],[3,4] ]
x

[[1, 2], [3, 4]]

In [16]:
y = np.array(x)
y

array([[1, 2],
       [3, 4]])

In [34]:
x = np.array([1,2,3,4])
y = np.array([[1,2],[2,3]])

In [35]:
x

array([1, 2, 3, 4])

In [36]:
y

array([[1, 2],
       [2, 3]])

#### Array Functions

In [37]:
np.info(x)

class:  ndarray
shape:  (4,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x278b35d1e30
byteorder:  little
byteswap:  False
type: int64


In [38]:
np.info(y)

class:  ndarray
shape:  (2, 2)
strides:  (16, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x278b35d13b0
byteorder:  little
byteswap:  False
type: int64


In [27]:
x.dtype,y.dtype

(dtype('int64'), dtype('int64'))

In [39]:
len(x)

4

In [40]:
len(y)

2

In [41]:
x.ndim

1

In [42]:
y.ndim

2

In [43]:
x.itemsize

8

In [44]:
y.itemsize

8

### Data Creation Functions

In [45]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [46]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [54]:
np.random.randint(10)

8

In [56]:
np.random.randint(10,100,100)

array([99, 49, 47, 89, 24, 74, 23, 60, 69, 21, 80, 13, 65, 48, 69, 40, 75,
       12, 46, 83, 54, 97, 21, 31, 65, 24, 80, 81, 66, 70, 77, 60, 67, 24,
       10, 63, 43, 95, 66, 87, 16, 80, 71, 89, 37, 93, 21, 21, 46, 34, 60,
       53, 93, 66, 54, 87, 47, 75, 62, 26, 77, 55, 69, 47, 55, 62, 20, 92,
       94, 79, 31, 92, 99, 74, 70, 84, 90, 56, 87, 19, 74, 13, 72, 15, 65,
       74, 50, 60, 81, 29, 88, 76, 56, 57, 49, 85, 78, 85, 83, 66],
      dtype=int32)

In [64]:
np.random.rand(10)

array([0.18057018, 0.98703694, 0.49153797, 0.34896391, 0.70414715,
       0.93553782, 0.3038561 , 0.54025487, 0.90687388, 0.4586773 ])

##### normal distribution of data

In [70]:
np.random.randn(10)

array([ 1.07281439, -0.07108757, -0.94546524,  0.2223129 , -0.46319676,
       -0.49451179,  0.02769882,  0.21521511, -1.00782815, -1.17374873])

In [76]:
np.random.randn(1000000) .mean()

np.float64(-0.0003161721616284433)

In [77]:
np.random.randn(10) .std()

np.float64(1.1737756569261169)

#### Creating 2D array using random

In [80]:
x = np.random.randint(0,10,(2,2))
x

array([[1, 4],
       [6, 4]], dtype=int32)

In [81]:
y=np.random.randint(0,10,(2,2))
y

array([[2, 9],
       [0, 0]], dtype=int32)

In [82]:
z = 10

In [83]:
np.add(x,y)

array([[ 3, 13],
       [ 6,  4]], dtype=int32)

In [85]:
x=np.random.randint(0,10,(5,5))
x

array([[5, 5, 2, 6, 3],
       [0, 4, 8, 3, 9],
       [1, 8, 4, 3, 2],
       [2, 0, 3, 0, 7],
       [8, 1, 2, 8, 1]], dtype=int32)

In [86]:
x[2:5,3:5]

array([[3, 2],
       [0, 7],
       [8, 1]], dtype=int32)

In [87]:
x[3:5,2:4]

array([[3, 0],
       [2, 8]], dtype=int32)

In [89]:
x[-3:-1,-5:-2]

array([[1, 8, 4],
       [2, 0, 3]], dtype=int32)

### Built In Functions

In [90]:
x = np.random.randint(0,10,(2,2))
y = np.random.randint(0,10,(2,2))

In [91]:
x

array([[6, 8],
       [9, 6]], dtype=int32)

In [92]:
y

array([[7, 7],
       [6, 3]], dtype=int32)

In [93]:
np.add(x,y)

array([[13, 15],
       [15,  9]], dtype=int32)

In [94]:
np.subtract(x,y)

array([[-1,  1],
       [ 3,  3]], dtype=int32)

In [95]:
np.multiply(x,y)

array([[42, 56],
       [54, 18]], dtype=int32)

In [96]:
np.divide(x,y)

array([[0.85714286, 1.14285714],
       [1.5       , 2.        ]])

In [97]:
np.floor_divide(x,y)

array([[0, 1],
       [1, 2]], dtype=int32)

In [98]:
np.mod(x,y)

array([[6, 1],
       [3, 0]], dtype=int32)

In [99]:
np.power(x,2)

array([[36, 64],
       [81, 36]], dtype=int32)

In [100]:
np.power(y,3)

array([[343, 343],
       [216,  27]], dtype=int32)

#### Round off

In [101]:
y=np.array([[1.6,2.3],[3.5,3.9]])
y

array([[1.6, 2.3],
       [3.5, 3.9]])

In [102]:
np.round(y)

array([[2., 2.],
       [4., 4.]])

In [103]:
y=np.array([[-1.6,-2.3,-3.5,-3.9]])
y

array([[-1.6, -2.3, -3.5, -3.9]])

In [104]:
np.round(y)

array([[-2., -2., -4., -4.]])

In [105]:
y = np.array([1.6, 2.3, 3.5, 3.9])

In [106]:
y

array([1.6, 2.3, 3.5, 3.9])

In [107]:
np.floor(y)

array([1., 2., 3., 3.])

In [108]:
np.ceil(y)

array([2., 3., 4., 4.])

In [109]:
np.fix(y)

array([1., 2., 3., 3.])

In [110]:
y = np.array([-1.6, -2.3, -3.5, -3.9])
y

array([-1.6, -2.3, -3.5, -3.9])

In [111]:
np.floor(y)

array([-2., -3., -4., -4.])

In [112]:
np.ceil(y)

array([-1., -2., -3., -3.])

In [113]:
np.fix(y)

array([-1., -2., -3., -3.])

### log and exponential

In [114]:
import math
math.e

2.718281828459045

In [115]:
math.pi

3.141592653589793

In [116]:
math.tau

6.283185307179586

In [117]:
np.exp(-2)

np.float64(0.1353352832366127)

In [118]:
np.power(2.718281828459045,-2)

np.float64(0.1353352832366127)

In [119]:
np.exp(2)

np.float64(7.38905609893065)

In [120]:
np.expm1(2)

np.float64(6.38905609893065)

In [121]:
x

array([[6, 8],
       [9, 6]], dtype=int32)

In [122]:
y

array([-1.6, -2.3, -3.5, -3.9])

In [123]:
-1*y

array([1.6, 2.3, 3.5, 3.9])

In [124]:
y*-1

array([1.6, 2.3, 3.5, 3.9])

In [125]:
y

array([-1.6, -2.3, -3.5, -3.9])

In [126]:
-1*y

array([1.6, 2.3, 3.5, 3.9])

In [127]:
y

array([-1.6, -2.3, -3.5, -3.9])

In [128]:
np.exp(y)

array([0.20189652, 0.10025884, 0.03019738, 0.02024191])

In [130]:
-1*y

array([1.6, 2.3, 3.5, 3.9])

In [132]:
y
np.exp(y)

array([0.20189652, 0.10025884, 0.03019738, 0.02024191])

In [133]:
np.log(math.e)

np.float64(1.0)

In [134]:
np.log2(2)

np.float64(1.0)

In [135]:
np.log10(10)

np.float64(1.0)

In [136]:
np.log2(16)

np.float64(4.0)

###  statistical functions

In [138]:
data=np.array([10,11,15,21,36,1000])

In [139]:
np.mean(data)

np.float64(182.16666666666666)

In [140]:
(10+11+15+21+36+1000)

1093

In [141]:
(10+11+15+21+36+1000)/6

182.16666666666666

In [142]:
np.median(data)

np.float64(18.0)

In [143]:
data=np.array([-20,0,30,50,10])

In [144]:
(data-data.mean())/len(data)

array([-6.8, -2.8,  3.2,  7.2, -0.8])

In [145]:
data.mean()

np.float64(14.0)

In [146]:
len(data)

5

In [147]:
data-data.mean()

array([-34., -14.,  16.,  36.,  -4.])

In [148]:
np.std(data)

np.float64(24.166091947189145)

In [149]:
np.sqrt(sum((data-data.mean())**2)/5)

np.float64(24.166091947189145)

In [150]:
np.var(data)

np.float64(584.0)

In [151]:
data

array([-20,   0,  30,  50,  10])

In [152]:
np.quantile(data,0.25)

np.float64(0.0)

In [153]:
np.quantile(data,0.50)

np.float64(10.0)

In [154]:
np.quantile(data,0.75)

np.float64(30.0)

In [155]:
np.min(data)

np.int64(-20)

In [156]:
np.max(data)

np.int64(50)

### Trignometric Functions

In [157]:
x = 2

In [159]:
x
np.sin(x)

np.float64(0.9092974268256817)

In [160]:
np.cos(x),np.tan(x)

(np.float64(-0.4161468365471424), np.float64(-2.185039863261519))

In [161]:
np.arcsin(x)

C:\Users\cherry\AppData\Local\Temp\ipykernel_13160\1524129805.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(x)


np.float64(nan)

In [162]:
np.arctan(x)

np.float64(1.1071487177940904)

In [163]:
np.sinh(x),np.cosh(x),np.tanh(x)

(np.float64(3.6268604078470186),
 np.float64(3.7621956910836314),
 np.float64(0.9640275800758169))

In [164]:
x=np.array([10,9,8,7])

In [165]:
x

array([10,  9,  8,  7])

In [166]:
np.sum(x)

np.int64(34)

In [167]:
np.prod(x)

np.int64(5040)

In [168]:
np.cumsum(x)

array([10, 19, 27, 34])

In [169]:
np.cumprod(x)

array([  10,   90,  720, 5040])

### axis = 0 , axis = 1

In [171]:
x=np.random.randint(0,10,(3,3))
x

array([[0, 6, 4],
       [9, 1, 0],
       [6, 6, 4]], dtype=int32)

In [172]:
x.sum()

np.int64(36)

In [173]:
x.sum(axis=0)

array([15, 13,  8])

In [174]:
x.sum(axis=1)

array([10, 10, 16])

In [175]:
x=np.random.randint(0,2,(4,4))

In [176]:
x

array([[1, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [1, 0, 0, 1]], dtype=int32)

In [179]:
x.mean()

np.float64(0.5625)

In [180]:
x.mean(axis = 0)

array([0.5 , 0.75, 0.75, 0.25])

In [181]:
x.mean(axis = 1)

array([0.75, 0.5 , 0.5 , 0.5 ])

In [182]:
x=np.random.randint(0,10,(4,4))

In [183]:
x

array([[6, 7, 9, 5],
       [9, 2, 2, 9],
       [9, 1, 4, 4],
       [5, 6, 1, 9]], dtype=int32)

In [184]:
x.max(axis=0)

array([9, 7, 9, 9], dtype=int32)

In [185]:
x.max(axis = 1)

array([9, 9, 9, 9], dtype=int32)

In [186]:
x.argmax(axis=0)

array([1, 0, 0, 1])

In [187]:
x.argmax(axis=1)

array([2, 0, 0, 3])

In [188]:
x.argmin(axis=0)

array([3, 2, 3, 2])

In [189]:
x.argmin(axis=1)

array([3, 1, 1, 2])

In [190]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [191]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [192]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [193]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

### where, any, all

In [194]:
data=np.random.randint(0,100,10)
data

array([63, 24, 63, 22, 75, 47, 37, 45, 54, 64], dtype=int32)

In [195]:
data>50

array([ True, False,  True, False,  True, False, False, False,  True,
        True])

In [196]:
data[data>50]

array([63, 63, 75, 54, 64], dtype=int32)

In [197]:
np.where(data>50,"high","low")

array(['high', 'low', 'high', 'low', 'high', 'low', 'low', 'low', 'high',
       'high'], dtype='<U4')

In [198]:
np.any(data>50)

np.True_

In [199]:
np.all(data>50)

np.False_

In [203]:
np.all(data>0)

np.True_