In [1]:
import numpy as np

In [2]:
array = np.random.randint(0,10,10)

In [3]:
array

array([3, 0, 1, 3, 6, 5, 8, 8, 8, 0], dtype=int32)

In [5]:
array.shape

(10,)

In [6]:
array.reshape(1,10)

array([[3, 0, 1, 3, 6, 5, 8, 8, 8, 0]], dtype=int32)

In [7]:
data=np.random.randint(0,10,(3,3))

In [8]:
data

array([[6, 8, 0],
       [2, 2, 0],
       [6, 6, 0]], dtype=int32)

In [9]:
y = data.ravel()

In [10]:
y

array([6, 8, 0, 2, 2, 0, 6, 6, 0], dtype=int32)

In [11]:
y[0]=200

In [12]:
y

array([200,   8,   0,   2,   2,   0,   6,   6,   0], dtype=int32)

In [13]:
data

array([[200,   8,   0],
       [  2,   2,   0],
       [  6,   6,   0]], dtype=int32)

In [15]:
data=np.random.randint(0,10,(3,3))

In [16]:
data

array([[3, 7, 0],
       [0, 6, 0],
       [2, 3, 7]], dtype=int32)

In [17]:
x = data.flatten()

In [18]:
x

array([3, 7, 0, 0, 6, 0, 2, 3, 7], dtype=int32)

In [19]:
x[0]=500

In [20]:
x

array([500,   7,   0,   0,   6,   0,   2,   3,   7], dtype=int32)

In [21]:
data

array([[3, 7, 0],
       [0, 6, 0],
       [2, 3, 7]], dtype=int32)

In [22]:
data = np.random.randint(0,10,(3,3))

In [23]:
data

array([[1, 3, 4],
       [6, 0, 0],
       [3, 3, 8]], dtype=int32)

In [24]:
data.T

array([[1, 6, 3],
       [3, 0, 3],
       [4, 0, 8]], dtype=int32)

In [25]:
x=np.random.randint(0,10,(3,3))

In [26]:
y=np.random.randint(0,10,(3,3))

In [27]:
x

array([[4, 6, 2],
       [7, 4, 4],
       [8, 5, 5]], dtype=int32)

In [28]:
y

array([[7, 5, 1],
       [6, 2, 2],
       [4, 9, 9]], dtype=int32)

In [29]:
np.vstack((x,y))

array([[4, 6, 2],
       [7, 4, 4],
       [8, 5, 5],
       [7, 5, 1],
       [6, 2, 2],
       [4, 9, 9]], dtype=int32)

In [30]:
np.hstack((x,y))

array([[4, 6, 2, 7, 5, 1],
       [7, 4, 4, 6, 2, 2],
       [8, 5, 5, 4, 9, 9]], dtype=int32)

In [31]:
data=np.random.randint(0,10,(4,4))

In [32]:
data

array([[3, 8, 3, 6],
       [2, 0, 3, 6],
       [4, 5, 5, 6],
       [7, 3, 8, 0]], dtype=int32)

In [33]:
np.split(data,2,axis = 0)

[array([[3, 8, 3, 6],
        [2, 0, 3, 6]], dtype=int32),
 array([[4, 5, 5, 6],
        [7, 3, 8, 0]], dtype=int32)]

In [34]:
np.split(data,2,axis = 1)

[array([[3, 8],
        [2, 0],
        [4, 5],
        [7, 3]], dtype=int32),
 array([[3, 6],
        [3, 6],
        [5, 6],
        [8, 0]], dtype=int32)]

In [35]:
np.vsplit(data,2)

[array([[3, 8, 3, 6],
        [2, 0, 3, 6]], dtype=int32),
 array([[4, 5, 5, 6],
        [7, 3, 8, 0]], dtype=int32)]

In [36]:
np.hsplit(data,2)

[array([[3, 8],
        [2, 0],
        [4, 5],
        [7, 3]], dtype=int32),
 array([[3, 6],
        [3, 6],
        [5, 6],
        [8, 0]], dtype=int32)]

### Set Functions

In [37]:
a = np.array([1, 2, 3, 4, 5, 2, 3])
b = np.array([4, 5, 6, 7])

In [38]:
a

array([1, 2, 3, 4, 5, 2, 3])

In [39]:
b

array([4, 5, 6, 7])

In [40]:
np.unique(a)

array([1, 2, 3, 4, 5])

In [41]:
np.intersect1d(a,b)

array([4, 5])

In [42]:
np.setdiff1d(b,a)

array([6, 7])

In [45]:
np.in1d(a,b)

C:\Users\cherry\AppData\Local\Temp\ipykernel_1920\1278926644.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a,b)


array([False, False, False,  True,  True, False, False])

## Some Examples 

In [46]:
sales=np.random.randint(10,100,10)

In [47]:
sales

array([27, 17, 16, 98, 26, 68, 72, 41, 19, 87], dtype=int32)

In [48]:
sales[sales>50]

array([98, 68, 72, 87], dtype=int32)

In [49]:
sales[sales>sales.mean()]

array([98, 68, 72, 87], dtype=int32)

In [50]:
sales.mean()

np.float64(47.1)

In [51]:
sales[sales<=sales.mean()]

array([27, 17, 16, 26, 41, 19], dtype=int32)

In [52]:
sales=np.random.randint(1,100,(10,5))

In [53]:
sales

array([[98, 87, 94, 89, 29],
       [27, 30, 90, 89, 69],
       [86, 87, 93, 82, 60],
       [31, 89, 90, 88, 66],
       [ 5, 96, 90, 21, 45],
       [ 2, 83,  5, 91, 21],
       [45, 30, 55, 75, 13],
       [42, 13, 93, 27, 41],
       [62, 44, 67, 64, 77],
       [34, 41, 88, 19, 91]], dtype=int32)

In [54]:
sales.sum(axis=1)

array([397, 305, 408, 364, 257, 202, 218, 216, 314, 273])

In [55]:
sales.sum(axis=0)

array([432, 600, 765, 645, 512])

In [56]:
sales[:,0]

array([98, 27, 86, 31,  5,  2, 45, 42, 62, 34], dtype=int32)

In [58]:
sales[:,0].max()

np.int32(98)

In [59]:
sales[:,0].argmax()+1

np.int64(1)

In [60]:
sales.mean(axis=0)

array([43.2, 60. , 76.5, 64.5, 51.2])

In [61]:
sales.mean(axis=0).argmax()+1

np.int64(3)

In [62]:
sales

array([[98, 87, 94, 89, 29],
       [27, 30, 90, 89, 69],
       [86, 87, 93, 82, 60],
       [31, 89, 90, 88, 66],
       [ 5, 96, 90, 21, 45],
       [ 2, 83,  5, 91, 21],
       [45, 30, 55, 75, 13],
       [42, 13, 93, 27, 41],
       [62, 44, 67, 64, 77],
       [34, 41, 88, 19, 91]], dtype=int32)

In [63]:
(sales[:,0]/sales[:,2]).argmax()

np.int64(0)

In [64]:
(sales[:,0]/sales[:,2]).astype(int)

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
import numpy as np

data = np.array([
    [11, 86, 30, 35, 20, 0],
    [63, 66, 3, 1, 47, 1],
    [21, 52, 80, 74, 71, 0],
    [71, 58, 79, 90, 44, 1],
    [35, 64, 79, 23, 50, 0],
    [19, 42, 84, 59, 59, 0],
    [68, 11, 27, 27, 89, 1],
    [99, 27, 5, 14, 72, 0],
    [10, 96, 61, 18, 80, 1],
    [18, 33, 18, 52, 78, 0]
])

print(data)

[[11 86 30 35 20  0]
 [63 66  3  1 47  1]
 [21 52 80 74 71  0]
 [71 58 79 90 44  1]
 [35 64 79 23 50  0]
 [19 42 84 59 59  0]
 [68 11 27 27 89  1]
 [99 27  5 14 72  0]
 [10 96 61 18 80  1]
 [18 33 18 52 78  0]]


In [66]:
data[data[:,-1]==0]

array([[11, 86, 30, 35, 20,  0],
       [21, 52, 80, 74, 71,  0],
       [35, 64, 79, 23, 50,  0],
       [19, 42, 84, 59, 59,  0],
       [99, 27,  5, 14, 72,  0],
       [18, 33, 18, 52, 78,  0]])

In [67]:
data[data[:,-1]==1]

array([[63, 66,  3,  1, 47,  1],
       [71, 58, 79, 90, 44,  1],
       [68, 11, 27, 27, 89,  1],
       [10, 96, 61, 18, 80,  1]])

In [68]:
if data[data[:,-1]==0].sum()>data[data[:,-1]==1].sum():
    print("No drive through stores are giving more sales")
else:
    print("yes")

No drive through stores are giving more sales


In [69]:
data[data[:,-1]==0].sum()

np.int64(1410)

In [70]:
data[data[:,-1]==1].sum()

np.int64(1013)